// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaInputChannel.proto

#include "MediaInputChannel.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_AudioConfig_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AudioConfig_AudioConfig_2eproto;
namespace tag {
namespace aas {
class MediaInputChannelDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MediaInputChannel> _instance;
} _MediaInputChannel_default_instance_;
}  // namespace aas
}  // namespace tag
static void InitDefaultsscc_info_MediaInputChannel_MediaInputChannel_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tag::aas::_MediaInputChannel_default_instance_;
    new (ptr) ::tag::aas::MediaInputChannel();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tag::aas::MediaInputChannel::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MediaInputChannel_MediaInputChannel_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MediaInputChannel_MediaInputChannel_2eproto}, {
      &scc_info_AudioConfig_AudioConfig_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_MediaInputChannel_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_MediaInputChannel_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_MediaInputChannel_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_MediaInputChannel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::tag::aas::MediaInputChannel, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::MediaInputChannel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tag::aas::MediaInputChannel, stream_type_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::MediaInputChannel, audio_config_),
  1,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::tag::aas::MediaInputChannel)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tag::aas::_MediaInputChannel_default_instance_),
};

const char descriptor_table_protodef_MediaInputChannel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027MediaInputChannel.proto\022\007tag.aas\032\025Medi"
  "aStreamType.proto\032\021AudioConfig.proto\"s\n\021"
  "MediaInputChannel\0222\n\013stream_type\030\001 \002(\0162\035"
  ".tag.aas.MediaStreamType.Enum\022*\n\014audio_c"
  "onfig\030\002 \002(\0132\024.tag.aas.AudioConfig"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_MediaInputChannel_2eproto_deps[2] = {
  &::descriptor_table_AudioConfig_2eproto,
  &::descriptor_table_MediaStreamType_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_MediaInputChannel_2eproto_sccs[1] = {
  &scc_info_MediaInputChannel_MediaInputChannel_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_MediaInputChannel_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MediaInputChannel_2eproto = {
  false, false, descriptor_table_protodef_MediaInputChannel_2eproto, "MediaInputChannel.proto", 193,
  &descriptor_table_MediaInputChannel_2eproto_once, descriptor_table_MediaInputChannel_2eproto_sccs, descriptor_table_MediaInputChannel_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_MediaInputChannel_2eproto::offsets,
  file_level_metadata_MediaInputChannel_2eproto, 1, file_level_enum_descriptors_MediaInputChannel_2eproto, file_level_service_descriptors_MediaInputChannel_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MediaInputChannel_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_MediaInputChannel_2eproto)), true);
namespace tag {
namespace aas {

// ===================================================================

void MediaInputChannel::InitAsDefaultInstance() {
  ::tag::aas::_MediaInputChannel_default_instance_._instance.get_mutable()->audio_config_ = const_cast< ::tag::aas::AudioConfig*>(
      ::tag::aas::AudioConfig::internal_default_instance());
}
class MediaInputChannel::_Internal {
 public:
  using HasBits = decltype(std::declval<MediaInputChannel>()._has_bits_);
  static void set_has_stream_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::tag::aas::AudioConfig& audio_config(const MediaInputChannel* msg);
  static void set_has_audio_config(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

const ::tag::aas::AudioConfig&
MediaInputChannel::_Internal::audio_config(const MediaInputChannel* msg) {
  return *msg->audio_config_;
}
void MediaInputChannel::clear_audio_config() {
  if (audio_config_ != nullptr) audio_config_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
MediaInputChannel::MediaInputChannel(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tag.aas.MediaInputChannel)
}
MediaInputChannel::MediaInputChannel(const MediaInputChannel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_audio_config()) {
    audio_config_ = new ::tag::aas::AudioConfig(*from.audio_config_);
  } else {
    audio_config_ = nullptr;
  }
  stream_type_ = from.stream_type_;
  // @@protoc_insertion_point(copy_constructor:tag.aas.MediaInputChannel)
}

void MediaInputChannel::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MediaInputChannel_MediaInputChannel_2eproto.base);
  ::memset(&audio_config_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&stream_type_) -
      reinterpret_cast<char*>(&audio_config_)) + sizeof(stream_type_));
}

MediaInputChannel::~MediaInputChannel() {
  // @@protoc_insertion_point(destructor:tag.aas.MediaInputChannel)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MediaInputChannel::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete audio_config_;
}

void MediaInputChannel::ArenaDtor(void* object) {
  MediaInputChannel* _this = reinterpret_cast< MediaInputChannel* >(object);
  (void)_this;
}
void MediaInputChannel::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MediaInputChannel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MediaInputChannel& MediaInputChannel::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MediaInputChannel_MediaInputChannel_2eproto.base);
  return *internal_default_instance();
}


void MediaInputChannel::Clear() {
// @@protoc_insertion_point(message_clear_start:tag.aas.MediaInputChannel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(audio_config_ != nullptr);
    audio_config_->Clear();
  }
  stream_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MediaInputChannel::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .tag.aas.MediaStreamType.Enum stream_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::tag::aas::MediaStreamType_Enum_IsValid(val))) {
            _internal_set_stream_type(static_cast<::tag::aas::MediaStreamType_Enum>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required .tag.aas.AudioConfig audio_config = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_audio_config(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MediaInputChannel::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tag.aas.MediaInputChannel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .tag.aas.MediaStreamType.Enum stream_type = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_stream_type(), target);
  }

  // required .tag.aas.AudioConfig audio_config = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::audio_config(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tag.aas.MediaInputChannel)
  return target;
}

size_t MediaInputChannel::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:tag.aas.MediaInputChannel)
  size_t total_size = 0;

  if (_internal_has_audio_config()) {
    // required .tag.aas.AudioConfig audio_config = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *audio_config_);
  }

  if (_internal_has_stream_type()) {
    // required .tag.aas.MediaStreamType.Enum stream_type = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_stream_type());
  }

  return total_size;
}
size_t MediaInputChannel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tag.aas.MediaInputChannel)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .tag.aas.AudioConfig audio_config = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *audio_config_);

    // required .tag.aas.MediaStreamType.Enum stream_type = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_stream_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MediaInputChannel::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tag.aas.MediaInputChannel)
  GOOGLE_DCHECK_NE(&from, this);
  const MediaInputChannel* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MediaInputChannel>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tag.aas.MediaInputChannel)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tag.aas.MediaInputChannel)
    MergeFrom(*source);
  }
}

void MediaInputChannel::MergeFrom(const MediaInputChannel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tag.aas.MediaInputChannel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_audio_config()->::tag::aas::AudioConfig::MergeFrom(from._internal_audio_config());
    }
    if (cached_has_bits & 0x00000002u) {
      stream_type_ = from.stream_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void MediaInputChannel::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tag.aas.MediaInputChannel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MediaInputChannel::CopyFrom(const MediaInputChannel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tag.aas.MediaInputChannel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MediaInputChannel::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_audio_config()) {
    if (!audio_config_->IsInitialized()) return false;
  }
  return true;
}

void MediaInputChannel::InternalSwap(MediaInputChannel* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MediaInputChannel, stream_type_)
      + sizeof(MediaInputChannel::stream_type_)
      - PROTOBUF_FIELD_OFFSET(MediaInputChannel, audio_config_)>(
          reinterpret_cast<char*>(&audio_config_),
          reinterpret_cast<char*>(&other->audio_config_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MediaInputChannel::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace aas
}  // namespace tag
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tag::aas::MediaInputChannel* Arena::CreateMaybeMessage< ::tag::aas::MediaInputChannel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tag::aas::MediaInputChannel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
