// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TouchEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TouchEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TouchEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "TouchAction.pb.h"
#include "TouchLocation.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TouchEvent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TouchEvent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TouchEvent_2eproto;
namespace tag {
namespace aas {
class TouchEvent;
class TouchEventDefaultTypeInternal;
extern TouchEventDefaultTypeInternal _TouchEvent_default_instance_;
}  // namespace aas
}  // namespace tag
PROTOBUF_NAMESPACE_OPEN
template<> ::tag::aas::TouchEvent* Arena::CreateMaybeMessage<::tag::aas::TouchEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tag {
namespace aas {

// ===================================================================

class TouchEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tag.aas.TouchEvent) */ {
 public:
  inline TouchEvent() : TouchEvent(nullptr) {};
  virtual ~TouchEvent();

  TouchEvent(const TouchEvent& from);
  TouchEvent(TouchEvent&& from) noexcept
    : TouchEvent() {
    *this = ::std::move(from);
  }

  inline TouchEvent& operator=(const TouchEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline TouchEvent& operator=(TouchEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TouchEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TouchEvent* internal_default_instance() {
    return reinterpret_cast<const TouchEvent*>(
               &_TouchEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TouchEvent& a, TouchEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(TouchEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TouchEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TouchEvent* New() const final {
    return CreateMaybeMessage<TouchEvent>(nullptr);
  }

  TouchEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TouchEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TouchEvent& from);
  void MergeFrom(const TouchEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TouchEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tag.aas.TouchEvent";
  }
  protected:
  explicit TouchEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TouchEvent_2eproto);
    return ::descriptor_table_TouchEvent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTouchLocationFieldNumber = 1,
    kTouchActionFieldNumber = 3,
  };
  // repeated .tag.aas.TouchLocation touch_location = 1;
  int touch_location_size() const;
  private:
  int _internal_touch_location_size() const;
  public:
  void clear_touch_location();
  ::tag::aas::TouchLocation* mutable_touch_location(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tag::aas::TouchLocation >*
      mutable_touch_location();
  private:
  const ::tag::aas::TouchLocation& _internal_touch_location(int index) const;
  ::tag::aas::TouchLocation* _internal_add_touch_location();
  public:
  const ::tag::aas::TouchLocation& touch_location(int index) const;
  ::tag::aas::TouchLocation* add_touch_location();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tag::aas::TouchLocation >&
      touch_location() const;

  // required .tag.aas.TouchAction touch_action = 3;
  bool has_touch_action() const;
  private:
  bool _internal_has_touch_action() const;
  public:
  void clear_touch_action();
  ::tag::aas::TouchAction touch_action() const;
  void set_touch_action(::tag::aas::TouchAction value);
  private:
  ::tag::aas::TouchAction _internal_touch_action() const;
  void _internal_set_touch_action(::tag::aas::TouchAction value);
  public:

  // @@protoc_insertion_point(class_scope:tag.aas.TouchEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tag::aas::TouchLocation > touch_location_;
  int touch_action_;
  friend struct ::TableStruct_TouchEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TouchEvent

// repeated .tag.aas.TouchLocation touch_location = 1;
inline int TouchEvent::_internal_touch_location_size() const {
  return touch_location_.size();
}
inline int TouchEvent::touch_location_size() const {
  return _internal_touch_location_size();
}
inline ::tag::aas::TouchLocation* TouchEvent::mutable_touch_location(int index) {
  // @@protoc_insertion_point(field_mutable:tag.aas.TouchEvent.touch_location)
  return touch_location_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tag::aas::TouchLocation >*
TouchEvent::mutable_touch_location() {
  // @@protoc_insertion_point(field_mutable_list:tag.aas.TouchEvent.touch_location)
  return &touch_location_;
}
inline const ::tag::aas::TouchLocation& TouchEvent::_internal_touch_location(int index) const {
  return touch_location_.Get(index);
}
inline const ::tag::aas::TouchLocation& TouchEvent::touch_location(int index) const {
  // @@protoc_insertion_point(field_get:tag.aas.TouchEvent.touch_location)
  return _internal_touch_location(index);
}
inline ::tag::aas::TouchLocation* TouchEvent::_internal_add_touch_location() {
  return touch_location_.Add();
}
inline ::tag::aas::TouchLocation* TouchEvent::add_touch_location() {
  // @@protoc_insertion_point(field_add:tag.aas.TouchEvent.touch_location)
  return _internal_add_touch_location();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tag::aas::TouchLocation >&
TouchEvent::touch_location() const {
  // @@protoc_insertion_point(field_list:tag.aas.TouchEvent.touch_location)
  return touch_location_;
}

// required .tag.aas.TouchAction touch_action = 3;
inline bool TouchEvent::_internal_has_touch_action() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TouchEvent::has_touch_action() const {
  return _internal_has_touch_action();
}
inline void TouchEvent::clear_touch_action() {
  touch_action_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::tag::aas::TouchAction TouchEvent::_internal_touch_action() const {
  return static_cast< ::tag::aas::TouchAction >(touch_action_);
}
inline ::tag::aas::TouchAction TouchEvent::touch_action() const {
  // @@protoc_insertion_point(field_get:tag.aas.TouchEvent.touch_action)
  return _internal_touch_action();
}
inline void TouchEvent::_internal_set_touch_action(::tag::aas::TouchAction value) {
  assert(::tag::aas::TouchAction_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  touch_action_ = value;
}
inline void TouchEvent::set_touch_action(::tag::aas::TouchAction value) {
  _internal_set_touch_action(value);
  // @@protoc_insertion_point(field_set:tag.aas.TouchEvent.touch_action)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace aas
}  // namespace tag

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TouchEvent_2eproto
