// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoConfig.proto

#include "VideoConfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace tag {
namespace aas {
class VideoConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<VideoConfig> _instance;
} _VideoConfig_default_instance_;
}  // namespace aas
}  // namespace tag
static void InitDefaultsscc_info_VideoConfig_VideoConfig_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tag::aas::_VideoConfig_default_instance_;
    new (ptr) ::tag::aas::VideoConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tag::aas::VideoConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_VideoConfig_VideoConfig_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_VideoConfig_VideoConfig_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_VideoConfig_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_VideoConfig_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_VideoConfig_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_VideoConfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, video_resolution_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, video_fps_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, margin_width_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, margin_height_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, dpi_),
  PROTOBUF_FIELD_OFFSET(::tag::aas::VideoConfig, additional_depth_),
  0,
  1,
  2,
  3,
  4,
  5,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::tag::aas::VideoConfig)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tag::aas::_VideoConfig_default_instance_),
};

const char descriptor_table_protodef_VideoConfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021VideoConfig.proto\022\007tag.aas\032\016VideoFps.p"
  "roto\032\025VideoResolution.proto\"\305\001\n\013VideoCon"
  "fig\0227\n\020video_resolution\030\001 \002(\0162\035.tag.aas."
  "VideoResolution.Enum\022)\n\tvideo_fps\030\002 \002(\0162"
  "\026.tag.aas.VideoFps.Enum\022\024\n\014margin_width\030"
  "\003 \002(\r\022\025\n\rmargin_height\030\004 \002(\r\022\013\n\003dpi\030\005 \002("
  "\r\022\030\n\020additional_depth\030\006 \001(\r"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_VideoConfig_2eproto_deps[2] = {
  &::descriptor_table_VideoFps_2eproto,
  &::descriptor_table_VideoResolution_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_VideoConfig_2eproto_sccs[1] = {
  &scc_info_VideoConfig_VideoConfig_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_VideoConfig_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_VideoConfig_2eproto = {
  false, false, descriptor_table_protodef_VideoConfig_2eproto, "VideoConfig.proto", 267,
  &descriptor_table_VideoConfig_2eproto_once, descriptor_table_VideoConfig_2eproto_sccs, descriptor_table_VideoConfig_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_VideoConfig_2eproto::offsets,
  file_level_metadata_VideoConfig_2eproto, 1, file_level_enum_descriptors_VideoConfig_2eproto, file_level_service_descriptors_VideoConfig_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_VideoConfig_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_VideoConfig_2eproto)), true);
namespace tag {
namespace aas {

// ===================================================================

void VideoConfig::InitAsDefaultInstance() {
}
class VideoConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<VideoConfig>()._has_bits_);
  static void set_has_video_resolution(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_video_fps(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_margin_width(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_margin_height(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_dpi(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_additional_depth(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000001f) ^ 0x0000001f) != 0;
  }
};

VideoConfig::VideoConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tag.aas.VideoConfig)
}
VideoConfig::VideoConfig(const VideoConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&video_resolution_, &from.video_resolution_,
    static_cast<size_t>(reinterpret_cast<char*>(&additional_depth_) -
    reinterpret_cast<char*>(&video_resolution_)) + sizeof(additional_depth_));
  // @@protoc_insertion_point(copy_constructor:tag.aas.VideoConfig)
}

void VideoConfig::SharedCtor() {
  ::memset(&video_resolution_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&additional_depth_) -
      reinterpret_cast<char*>(&video_resolution_)) + sizeof(additional_depth_));
}

VideoConfig::~VideoConfig() {
  // @@protoc_insertion_point(destructor:tag.aas.VideoConfig)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void VideoConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void VideoConfig::ArenaDtor(void* object) {
  VideoConfig* _this = reinterpret_cast< VideoConfig* >(object);
  (void)_this;
}
void VideoConfig::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void VideoConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VideoConfig& VideoConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_VideoConfig_VideoConfig_2eproto.base);
  return *internal_default_instance();
}


void VideoConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:tag.aas.VideoConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&video_resolution_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&additional_depth_) -
        reinterpret_cast<char*>(&video_resolution_)) + sizeof(additional_depth_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VideoConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .tag.aas.VideoResolution.Enum video_resolution = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::tag::aas::VideoResolution_Enum_IsValid(val))) {
            _internal_set_video_resolution(static_cast<::tag::aas::VideoResolution_Enum>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required .tag.aas.VideoFps.Enum video_fps = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::tag::aas::VideoFps_Enum_IsValid(val))) {
            _internal_set_video_fps(static_cast<::tag::aas::VideoFps_Enum>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required uint32 margin_width = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_margin_width(&has_bits);
          margin_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 margin_height = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_margin_height(&has_bits);
          margin_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 dpi = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_dpi(&has_bits);
          dpi_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 additional_depth = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_additional_depth(&has_bits);
          additional_depth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* VideoConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tag.aas.VideoConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .tag.aas.VideoResolution.Enum video_resolution = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_video_resolution(), target);
  }

  // required .tag.aas.VideoFps.Enum video_fps = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_video_fps(), target);
  }

  // required uint32 margin_width = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_margin_width(), target);
  }

  // required uint32 margin_height = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_margin_height(), target);
  }

  // required uint32 dpi = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_dpi(), target);
  }

  // optional uint32 additional_depth = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_additional_depth(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tag.aas.VideoConfig)
  return target;
}

size_t VideoConfig::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:tag.aas.VideoConfig)
  size_t total_size = 0;

  if (_internal_has_video_resolution()) {
    // required .tag.aas.VideoResolution.Enum video_resolution = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_video_resolution());
  }

  if (_internal_has_video_fps()) {
    // required .tag.aas.VideoFps.Enum video_fps = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_video_fps());
  }

  if (_internal_has_margin_width()) {
    // required uint32 margin_width = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_margin_width());
  }

  if (_internal_has_margin_height()) {
    // required uint32 margin_height = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_margin_height());
  }

  if (_internal_has_dpi()) {
    // required uint32 dpi = 5;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_dpi());
  }

  return total_size;
}
size_t VideoConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tag.aas.VideoConfig)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required .tag.aas.VideoResolution.Enum video_resolution = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_video_resolution());

    // required .tag.aas.VideoFps.Enum video_fps = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_video_fps());

    // required uint32 margin_width = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_margin_width());

    // required uint32 margin_height = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_margin_height());

    // required uint32 dpi = 5;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_dpi());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint32 additional_depth = 6;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000020u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_additional_depth());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VideoConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tag.aas.VideoConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const VideoConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<VideoConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tag.aas.VideoConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tag.aas.VideoConfig)
    MergeFrom(*source);
  }
}

void VideoConfig::MergeFrom(const VideoConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tag.aas.VideoConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      video_resolution_ = from.video_resolution_;
    }
    if (cached_has_bits & 0x00000002u) {
      video_fps_ = from.video_fps_;
    }
    if (cached_has_bits & 0x00000004u) {
      margin_width_ = from.margin_width_;
    }
    if (cached_has_bits & 0x00000008u) {
      margin_height_ = from.margin_height_;
    }
    if (cached_has_bits & 0x00000010u) {
      dpi_ = from.dpi_;
    }
    if (cached_has_bits & 0x00000020u) {
      additional_depth_ = from.additional_depth_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void VideoConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tag.aas.VideoConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VideoConfig::CopyFrom(const VideoConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tag.aas.VideoConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VideoConfig::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void VideoConfig::InternalSwap(VideoConfig* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VideoConfig, additional_depth_)
      + sizeof(VideoConfig::additional_depth_)
      - PROTOBUF_FIELD_OFFSET(VideoConfig, video_resolution_)>(
          reinterpret_cast<char*>(&video_resolution_),
          reinterpret_cast<char*>(&other->video_resolution_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VideoConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace aas
}  // namespace tag
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tag::aas::VideoConfig* Arena::CreateMaybeMessage< ::tag::aas::VideoConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tag::aas::VideoConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
